CREATE TABLE opportunityName (
  opportunityName_id INT NOT NULL AUTO_INCREMENT,
  description VARCHAR(1000) NOT NULL,
  PRIMARY KEY (opportunityName_id)
);

INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Soap Recycling 1:30 p.m. session (Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Soap Recycling 10 a.m. session (Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Daily Necessities to Homeless People in Sham Shui Po");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Help with sorting donated goods at Crossroads (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Collect Bread for Redistribution (Fortress Hill)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Help Ethnic Minority Children with homework in Jordan");
INSERT INTO opportunityName (description) VALUES ("Help Students with Intellectual Disabilities at Job-related Online Training");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Let''s Hike and Clean Up HK Trails (Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Daily Necessities to Homeless in TKT (Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Family Opportunity: Deliver Daily Necessities to Homeless People in Tai Kok Tsui");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Mong Kok");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Daily Necessities and Warmth to Homeless in CWB");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Fortress Hill");
INSERT INTO opportunityName (description) VALUES ("Family Opportunity: Deliver Daily Necessities and Warmth to Homeless in YMT");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Tai Kok Tsui");
INSERT INTO opportunityName (description) VALUES ("Family Opportunity: Help Out with Beach Cleaning in Sam Pak Wan");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Help Out at Mobile Literacy Program with the Elderly");
INSERT INTO opportunityName (description) VALUES ("Help and Be the Storyteller at Story Telling Corner with Children");
INSERT INTO opportunityName (description) VALUES ("Youth opportunity: Help at Food Station in Lai Chi Kok");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Help at Food Station in Lai Chi Kok (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Wan Chai");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Mong Kok (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Daily Necessities to Homeless in CWB (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Fortress Hill (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Warmth to Homeless in YMT(Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Tai Kok Tsui (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in YMT(Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Wan Chai (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Help at Play Group with Students with Physical Disabilities");
INSERT INTO opportunityName (description) VALUES ("Family Opportunity: Soap Recycling");
INSERT INTO opportunityName (description) VALUES ("Help Ethnic Minority Children with Homework in Jordan");
INSERT INTO opportunityName (description) VALUES ("Help Hearing-Impaired Children with Schoolwork in To Kwa Wan");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Sham Shui Po");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Tsim Sha Tsui");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Home Deliveries for People with Mental Illness in Tseung Kwan O");
INSERT INTO opportunityName (description) VALUES ("Phone call support to 1 elderly individual [PRE-TRAINED VOLUNTEERS ONLY]");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Distributing Care Packages for isolating elderly in Tai Po");
INSERT INTO opportunityName (description) VALUES ("Pre-recorded virtual storytelling for hospitalized children (English)");
INSERT INTO opportunityName (description) VALUES ("Pre-recorded virtual storytelling for hospitalized children (Cantonese)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Kwun Tong");
INSERT INTO opportunityName (description) VALUES ("2020 VF Purpose Day - Tree Maintenance");
INSERT INTO opportunityName (description) VALUES ("2020 VF Purpose Day - Wetland Habitat Preservation");
INSERT INTO opportunityName (description) VALUES ("2020 VF Purpose Week Pilot Program - Creating Educational Videos for Students");
INSERT INTO opportunityName (description) VALUES ("2020 VF Purpose Week - testing");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Packing Hygiene Kits distributed to Street Cleaners");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Deliver Necessities and Warmth to Homeless in Yau Ma Tei");
INSERT INTO opportunityName (description) VALUES ("Online training session: Phone call support for the elderly (COVID-19 relief)");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Home deliveries for isolating elderly in Chai Wan");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Home deliveries for isolating elderly in Sha Tin");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Home deliveries for isolating elderly in Sham Shui Po");
INSERT INTO opportunityName (description) VALUES ("COVID-19 Relief: Home deliveries for isolating elderly in Tin Shui Wai");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Kwun Tong (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Help Out with Beach Cleaning in Nim Shue Wan (Family Welcome)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Home deliveries for isolating elderly in Sham Shui Po");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Create gift cards for Care Packages (Virtual Volunteering)");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Pre-recorded Cantonese storytelling for hospitalized children");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Pre-recorded English storytelling for hospitalized children");
INSERT INTO opportunityName (description) VALUES ("LGT - (English) Phone call support to elderly [PRE-TRAINED VOLUNTEERS ONLY]");
INSERT INTO opportunityName (description) VALUES ("LGT - (Cantonese) Phone call support to elderly [PRE-TRAINED VOLUNTEERS ONLY]");
INSERT INTO opportunityName (description) VALUES ("Distributing Hygiene Kits to Street Cleaners");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Create a sensory box for a student with intellectual disabilities");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Create an ''Inspiration Jar'' for a SEN child");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Film a video greeting for an elderly person living in a care-home");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Organize a drive to raise emergency items for special needs kids");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Organize a drive to raise emergency items for low-income families");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Organize a drive to raise emergency items for vulnerable families");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Organize a drive to raise emergency items for the elderly people");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Organize a drive to raise emergency items for refugees");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver care packages for isolating elderly in Central");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver Necessities to Homeless in Tsim Sha Tsui (Youth Welcome)");
INSERT INTO opportunityName (description) VALUES ("HandsOn Care Pack Delivery Volunteer Leader Information and Training Session");
INSERT INTO opportunityName (description) VALUES ("Self-Reported Volunteer Hours");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Help at animal shelter in Yuen Long");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Help at animal shelter in Yuen Long");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Farming Experience Day with your families");
INSERT INTO opportunityName (description) VALUES ("Serve-A-Thon: Deliver care packages for isolating elderly in Kwai Chung");
INSERT INTO opportunityName (description) VALUES ("Serve-a-thon: Outreach to domestic workers and distribute the giveaway packets");
INSERT INTO opportunityName (description) VALUES ("Training session: Virtual storytelling for hospitalized children (Bilingual)");
INSERT INTO opportunityName (description) VALUES ("Training session: Virtual storytelling for hospitalized children (English)");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered: Create gift cards for the elderly (Virtual Volunteering)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunities: Preparing food ingredients and meal boxes in SSP Kitchen");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunities: Preparing food ingredients and meal boxes in Harvest Mill");
INSERT INTO opportunityName (description) VALUES ("Be a Sports Class Assistant for People with Special Needs");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Opportunity: Collect Bread for Redistribution (Admiralty)");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Opportunity: Collect Bread for Redistribution (Kwun Tong)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Collect Bread for Redistribution (Causeway Bay)");
INSERT INTO opportunityName (description) VALUES ("Youth Opportunity: Collect Bread for Redistribution (Tsim Sha Tsui)");
INSERT INTO opportunityName (description) VALUES ("Help at Play Group with Students with Intellectual Disabilities");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Opportunity: Collect Bread for Redistribution (Sheung Wan)");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Info Session: Providing support to refugee children");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Opportunity: Info Session on Reducing Plastic Usage");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Info Session: Be a ''Blind Buddy'' to support a student");
INSERT INTO opportunityName (description) VALUES ("Youth Empowered Info Session: Help a child with their homework through Zoom");

DROP TABLE opportunityName;
